# Generated by Django 4.2.4 on 2023-08-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_file',
            name='file1',
            field=models.FileField(upload_to='inputPage/SOURCE_DOCUMENTS/'),
        ),
    ]
